import java.util.Random;
import java.util.Scanner;

public class GuessGame {
     public static void main(String[] args){
        int MAX_attempts=15;
        Scanner sc=new Scanner(System.in);
        Random rd=new Random();
        System.out.println("Welcome User");
        System.out.println("The game begins with the user entering the number of attempts he wishes with the max number of attempts being 15");
        System.out.println("User should enter a number between 1 to 100");
        System.out.println("If the input from the user matches the random number generated by the system he/she gets awarded a point.");
        System.out.println("Rules:");
        System.out.println("1.The input must be in the range of 1 to 100");
        System.out.println("2.If the user wishes to terminate during the game enter 0 as the input and the game gest terminated");
        System.out.println();
        System.out.println("Enter Number of Attempts");
        int attempts=sc.nextInt();
        if(attempts>0&&attempts<=MAX_attempts){
            int inp=-1;
            int points=0,played=0;
            while(inp!=0&&attempts>0){
                System.out.println("Enter a Number");
                inp=sc.nextInt();
                int num=rd.nextInt(100);
                if(inp==num){
                    System.out.println("Hooray you scored a point");
                    points++;
                }
                else if(inp==0){
                    System.out.println("Thank you for playing with us");
                    System.out.println("Score: "+points+"/"+played);
                }
                else{
                    if(inp>num){
                        System.out.println("You missed it,Try lower");
                    }
                    else{
                        System.out.println("You missed it,Try Higher");
                    }
                }
                played++;
                attempts--;
            }
            if(attempts==0){
                System.out.println("Thank you for playing with us");
                    System.out.println("Score: "+points+"/"+played);
            }

        }
        sc.close();

    }

}
